@startuml
[newtonsoft] --> [Microsoft.CSharp 4.3.0]
[Microsoft.CSharp 4.3.0] --> [NETStandard.Library 1.6.1]
[Microsoft.CSharp 4.3.0] --> [System.ComponentModel.TypeConverter 4.3.0]
[Microsoft.CSharp 4.3.0] --> [System.Runtime.Serialization.Primitives 4.3.0]
[Microsoft.CSharp 4.3.0] --> [System.Runtime.Serialization.Formatters 4.3.0]
[Microsoft.CSharp 4.3.0] --> [System.Xml.XmlDocument 4.3.0]
[newtonsoft] --> [NETStandard.Library 1.6.1]
[NETStandard.Library 1.6.1] --> [System.ComponentModel.TypeConverter 4.3.0]
[NETStandard.Library 1.6.1] --> [System.Runtime.Serialization.Primitives 4.3.0]
[NETStandard.Library 1.6.1] --> [System.Runtime.Serialization.Formatters 4.3.0]
[NETStandard.Library 1.6.1] --> [System.Xml.XmlDocument 4.3.0]
[newtonsoft] --> [System.ComponentModel.TypeConverter 4.3.0]
[System.ComponentModel.TypeConverter 4.3.0] --> [System.Runtime.Serialization.Primitives 4.3.0]
[System.ComponentModel.TypeConverter 4.3.0] --> [System.Runtime.Serialization.Formatters 4.3.0]
[System.ComponentModel.TypeConverter 4.3.0] --> [System.Xml.XmlDocument 4.3.0]
[newtonsoft] --> [System.Runtime.Serialization.Primitives 4.3.0]
[System.Runtime.Serialization.Primitives 4.3.0] --> [System.Runtime.Serialization.Formatters 4.3.0]
[System.Runtime.Serialization.Primitives 4.3.0] --> [System.Xml.XmlDocument 4.3.0]
[newtonsoft] --> [System.Runtime.Serialization.Formatters 4.3.0]
[System.Runtime.Serialization.Formatters 4.3.0] --> [System.Xml.XmlDocument 4.3.0]
[newtonsoft] --> [System.Xml.XmlDocument 4.3.0]
@enduml
